include $(GOROOT)/src/Make.inc

TARG=jnwhiteh/minixfs
GOFILES=\
		blocks.go \
		bitmap.go \
		debug.go \
		device.go \
		dev_file.go \
		dev_ramdisk.go \
		cache.go \
		const.go \
		errors.go \
		file.go \
		filedes.go \
		fs.go \
		icache.go \
		link.go \
		macros.go \
		misc.go \
		mount.go \
		open.go \
		inode.go \
		path.go \
		read.go \
		super.go \
		types.go \
		write.go \

include $(GOROOT)/src/Make.pkg
