include $(GOROOT)/src/Make.inc

TARG=minixfs/common
GOFILES=\
		blocks.go \
		const.go \
		disk.go \
		errors.go \
		interfaces.go \
		read.go \
		super.go \
		write.go \
		types.go \

include $(GOROOT)/src/Make.pkg

